# Generated by Django 3.1.7 on 2021-03-14 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento', models.CharField(max_length=100, null=True)),
                ('categoria_estabelecimento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='controle_gastos_app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_de_pagamento', models.CharField(choices=[('Deb', 'Débito'), ('Din', 'Dinheiro'), ('Cre', 'Crédito')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateTimeField(auto_now=True, verbose_name=datetime.datetime.now)),
                ('estabelecimento', models.ForeignKey(default='Festval', on_delete=django.db.models.deletion.DO_NOTHING, to='controle_gastos_app.estabelecimento')),
                ('pagamento', models.OneToOneField(default='Deb', on_delete=django.db.models.deletion.CASCADE, to='controle_gastos_app.formapagamento')),
                ('usuario', models.OneToOneField(default='admin', on_delete=django.db.models.deletion.CASCADE, to='controle_gastos_app.usuario')),
                ('valor_gasto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='controle_gastos_app.valor')),
            ],
        ),
    ]
