# Generated by Django 3.1.7 on 2021-03-15 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagamento',
            name='forma_de_pagamento',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='pagamento',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='gasto',
            name='forma_pagamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='controle_gastos_app.formapagamento'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='nome_estabelecimento',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='estabelecimento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='controle_gastos_app.estabelecimento'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='controle_gastos_app.usuario'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor_gasto',
            field=models.FloatField(default=None),
        ),
        migrations.DeleteModel(
            name='Valor',
        ),
    ]
