# Generated by Django 3.1.7 on 2021-03-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorias',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='estabelecimentos',
            new_name='Estabelecimento',
        ),
        migrations.RenameModel(
            old_name='gastos',
            new_name='Gasto',
        ),
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
