# Generated by Django 3.1.7 on 2021-03-15 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos_app', '0002_auto_20210314_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='categoria_estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controle_gastos_app.categoria'),
        ),
    ]
