# Generated by Django 3.1.7 on 2021-03-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos_app', '0002_auto_20210314_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('B', 'Bar'), ('D', 'Delivery'), ('M', 'Mercado')], max_length=1, unique=True),
        ),
    ]
