# Generated by Django 3.1.7 on 2021-03-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos_app', '0003_auto_20210314_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_gastos_app.usuario'),
        ),
    ]
