# Generated by Django 3.1.7 on 2021-03-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos_app', '0004_auto_20210314_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='valor_gasto',
            field=models.FloatField(default=None, verbose_name=':.2f'),
        ),
    ]
