# Generated by Django 3.1.7 on 2021-03-15 02:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos_app', '0005_auto_20210314_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(db_column='Categoria', max_length=100),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='categoria_estabelecimento',
            field=models.ForeignKey(db_column='Categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='controle_gastos_app.categoria'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='nome_estabelecimento',
            field=models.CharField(blank=True, db_column='Estabelecimento', default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='pagamento',
            field=models.CharField(db_column='Forma de Pagamento', default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='data_pagamento',
            field=models.DateTimeField(auto_now=True, db_column='Data de Pagamento', verbose_name=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='estabelecimento',
            field=models.ForeignKey(db_column='Estabelecimento', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='controle_gastos_app.estabelecimento'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='forma_pagamento',
            field=models.ForeignKey(db_column='Forma de Pagamento', default=None, on_delete=django.db.models.deletion.CASCADE, to='controle_gastos_app.formapagamento'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(db_column='Usuário', on_delete=django.db.models.deletion.CASCADE, to='controle_gastos_app.usuario'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor_gasto',
            field=models.FloatField(db_column='Valor (R$)', default=None),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(db_column='Usuário', default=None, max_length=10),
        ),
    ]
